version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      # actions/deploy-pages 4.x requires actions/upload-artifact 4.x and is not compatible with withastro/action@v1, which is required to deploy the docs site.
      # Revisit when withastro/action@v2 is available.
      - dependency-name: actions/deploy-pages
        versions: ['4.x']

  - package-ecosystem: npm
    directory: '/sandbox'
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: '/docs'
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: '/packages/panda-preset'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/icons'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/react'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/react-aria'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/react-utils'
    schedule:
      interval: daily
