changesetIgnorePatterns:
  - '**/*.test.{js,jsx,ts,tsx}'
  - packages/*/tests/**

initScope: pluralsight

nodeLinker: pnp

npmPublishAccess: public

packageExtensions:
  '@docusaurus/utils@*':
    dependencies:
      react: '*'
      react-dom: '*'
  chalk@*:
    dependencies:
      '#ansi-styles': npm:ansi-styles@6.1.0
      '#supports-color': npm:supports-color@9.2.2
  native-or-bluebird@*:
    dependencies:
      bluebird: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: '@yarnpkg/plugin-exec'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

pnpMode: loose

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.1.cjs
