changesetIgnorePatterns:
  - '**/*.test.{js,ts}'

initScope: pluralsight

nodeLinker: pnp

npmPublishAccess: public

packageExtensions:
  '@docusaurus/utils@*':
    dependencies:
      react: '*'
      react-dom: '*'
  native-or-bluebird@*:
    dependencies:
      bluebird: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: '@yarnpkg/plugin-exec'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpMode: loose

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.1.cjs
