changesetIgnorePatterns:
  - '**/*.test.{js,jsx,ts,tsx}'
  - packages/*/tests/**

initScope: pluralsight

nodeLinker: pnp

npmPublishAccess: public

packageExtensions:
  '@docusaurus/utils@*':
    dependencies:
      react: '*'
      react-dom: '*'
  eslint@*:
    dependencies:
      '@typescript-eslint/parser': '*'
  '@pkgr/utils@*':
    dependencies:
      'react': '*'
      '@mdx-js/mdx': '*'
      'svelte': '*'
  '@testing-library/dom@*':
    dependencies:
      eslint-import-resolver-typescript: '*'
      eslint-import-resolver-node: '*'
  '@testing-library/user-event@*':
    dependencies:
      eslint-import-resolver-typescript: '*'
      eslint-import-resolver-node: '*'
  '@testing-library/react@*':
    dependencies:
      eslint-import-resolver-typescript: '*'
      eslint-import-resolver-node: '*'
  '@types/babel__core@*':
    dependencies:
      '@babel/generator': '*'
      '@babel/template': '*'
      '@babel/traverse': '*'
  '@types/react@*':
    dependencies:
      eslint-import-resolver-typescript: '*'
      eslint-import-resolver-node: '*'
      prop-types: '*'
      scheduler: '*'
  '@types/react-dom@*':
    dependencies:
      eslint-import-resolver-typescript: '*'
      react: '*'
  chalk@*:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@6.1.0'
      '#supports-color': 'npm:supports-color@9.2.2'
  native-or-bluebird@*:
    dependencies:
      bluebird: '*'
  rollup@*:
    dependencies:
      source-map-support: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: '@yarnpkg/plugin-exec'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

pnpMode: loose

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs
