# This file only exists for publishing to NPM as a TEMPORARY SOLUTION.
# Bun currently does not support publishing to NPM with a workspace dependency.

# Because all we care about are NPM packages, we can ignore everything else.

packages:
  - 'packages/*'
  - 'scripts'
  - 'configs'
