
# Note: this file's config overrides the Netlify UI admin config

# /!\ due to using a monorepo it can be a bit messy to configure Netlify
# See also https://github.com/netlify/build/issues/2483

[build]
  command = "yarn --cwd .. build:website"
  publish = "website/build"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "3.2.1"
  NODE_VERSION = "18.4.0"

[context.deploy-preview]
  command = "yarn --cwd .. build:website"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache/webpack",
  ]