on:
  pull_request_target:
    paths:
      - 'website/**'
  pull_request:
    paths:
      - 'website/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: 📖 Documentarians love
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: docs_template.md
