on:
  pull_request:
    paths:
      - 'website/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **We love our Documentarians**
            📖
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
