name: 🤖 Dependabot Dependency Install

on: pull_request

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

env:
  PR_URL: ${{github.event.pull_request.html_url}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure the git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Pull latest changes if needed
        run: |
          git config pull.rebase false
          git pull

      - name: Install dependencies
        run: |
          yarn --version
          yarn install

      - name: Commit the changes
        run: |
          git add .
          git commit -m "chore: update lock file"

      - name: Push the branch
        run: |
          git config push.autoSetupRemote true
          git push
