name: 📖 Documentation

on:
  push:
    paths:
      - 'website/**'
    branches:
      - main

jobs:
  gh-release:
    runs-on: ubuntu-latest
    name: 🚀 Release to GitHub Pages
    env:
      USE_SSH: true
      GIT_USER: ${{ secrets.GH_USERNAME }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          bun install
          bun run deploy:website
