name: 📖 Documentation

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: pnpm install
      - run: pnpm run build:icons

  build-and-upload:
    needs: build-icons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          path: './docs'
          package-manager: pnpm@latest

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        # actions/deploy-pages@v4 is pubicly available but requires actions/upload-pages-artifact@v4.
        # withastro/action@v1 uses actions/upload-pages-artifact@v2.
        # see https://github.com/withastro/action/pull/38 for additional details - update this action when it is possible.
