name: documentation

on:
  push:
    branches:
      - 'docs/**'
  pull_request:
    paths:
      - 'website/**'
    branches:
      - main

jobs:
  docs-build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    name: 👷‍♀️ Docs successfully build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build:website

  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: 🚀 Release to GitHub Pages
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          yarn install
          yarn deploy:website
