name: 💅 Lint Checks

on: [merge_group, pull_request]

jobs:
  lint-css:
    runs-on: ubuntu-latest
    name: CSS valid
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run lint:css

  lint-js:
    runs-on: ubuntu-latest
    name: JS valid
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run lint:js

  lint-ts:
    runs-on: ubuntu-latest
    name: TS valid
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run lint:ts

  lint-sandbox:
    runs-on: ubuntu-latest
    name: Sandbox valid
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run lint:sandbox
