name: 💅 Lint Checks

on: [merge_group, pull_request]

jobs:
  lint-css:
    runs-on: ubuntu-latest
    name: CSS valid
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: pnpm install
      - run: pnpm run lint:css

  lint-js:
    runs-on: ubuntu-latest
    name: JS valid
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: pnpm install
      - run: pnpm run lint:js

  lint-ts:
    runs-on: ubuntu-latest
    name: TS valid
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: pnpm install
      - run: pnpm run lint:ts

  lint-sandbox:
    runs-on: ubuntu-latest
    name: Sandbox valid
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: pnpm install
      - run: pnpm run lint:sandbox
