name: 💅 Lint Checks
run-name: ${{github.actor}} is testing something

on: [push]

jobs:
  lint-css:
    runs-on: ubuntu-latest
    name: 💅 Check for CSS errors
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint:css

  lint-js:
    runs-on: ubuntu-latest
    name: 💅 Check for JS errors
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint:js

  lint-ts:
    runs-on: ubuntu-latest
    name: 💅 Check for TS errors
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint:ts
